### ISSUE TITLE
[Questions] Please add guide document for setup Haskell environment with docker image

### ISSUE THREAD

**Issue by jimfang** [fp-works/2019-winter-Haskell-school#23]

**Comment by cht8687** [comment]
PR welcome!

**Comment by shineli1984** [comment]
@sinogermany may be able to help here as a docker user for Haskell. But if it's not a productive set up, please let us know.

**Comment by sinogermany** [comment]
> @sinogermany may be able to help here as a docker user for Haskell. But if it's not a productive set up, please let us know.

@shineli1984 Sorry just saw this. I'll try to come up with a document. At the same time, could you please look at [the build script](https://github.com/sinogermany/haskell-tutorial/blob/master/scripts/docker/dev-image-setup.sh) and let me know if there is anything you would suggest changing? Cheers!

**Comment by sinogermany** [comment]
@jimfang with the project setup, please have a look at [this repo](https://github.com/sinogermany/haskell-tutorial) and let me know if there's anything you would need more details of? I will try to raise a PR to this repo as a separate markdown documentation or in the wiki once I get your feedback. Cheers :)

**Comment by shineli1984** [comment]
@sinogermany Looks good. We can have this as a starting point.
