### ISSUE TITLE
[Questions] Please add guide document for how to setup a new project for haskell project

### ISSUE THREAD

**Issue by jimfang** [fp-works/2019-winter-Haskell-school#24]
something like a framework of new Haskell project.
for example "npx create-react-app my-app"

**Comment by cht8687** [comment]
we are adding, but the best way to learn is to find the answer yourself and update it on READ.MD yourself. 😄

**Comment by shineli1984** [comment]
@jimfang The README.md is updated. It's a starting point. Please have a look and see if it's helpful.

**Comment by shineli1984** [comment]
@cht8687 Could you please add the IDE set up for the vim/neovim section in the README.md?

**Comment by cht8687** [comment]
@shineli1984 I didn’t install any Haskell Plugins for Vim. 🤭 Will do if I find anything helpful.

**Comment by jimfang** [comment]
Readme is improved a lot. I can create new project with "stack new ...", also I can compile the file by "stack ghci <filename>".
But how to run unit test?  how to run the whole project as tool?

**Comment by stevemao** [comment]
`stack test` should run unit test. `stack build` should build the project

**Comment by jimfang** [comment]
dev-jimf10% stack test
'jimfang-0.1.0.0: unregistering (components added: test:jimfang-test)
jimfang> configure (lib + exe + test)
Configuring jimfang-0.1.0.0...
jimfang> build (lib + exe + test)
Preprocessing library for jimfang-0.1.0.0..
Building library for jimfang-0.1.0.0..
Preprocessing executable 'jimfang-exe' for jimfang-0.1.0.0..
Building executable 'jimfang-exe' for jimfang-0.1.0.0..
Preprocessing test suite 'jimfang-test' for jimfang-0.1.0.0..
Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: can't find source for Spec in
.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/jimfang-test/jimfang-test-tmp,
test                 
                     
                     
--  While building package jimfang-0.1.0.0 using:
      /Users/jimf/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build lib:jimfang exe:jimfang-exe test:jimfang-test --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 1/2

**Comment by shineli1984** [comment]
What's in your Spec.hs?
