### ISSUE TITLE
[TIL] Install Hoogle on your local machine and use it with GHCi

### ISSUE THREAD

**Issue by cht8687** [fp-works/2019-winter-Haskell-school#29]
![Screen Shot 2019-08-17 at 4 28 44 pm](https://user-images.githubusercontent.com/4587603/63207600-41d8b400-c10c-11e9-9f07-c00a006cbb88.png)

$ cabal install hoogle

:def hoogle \s -> return $ ":! hoogle --count=15 \"" ++ s ++ "\""

**Comment by stevemao** [comment]
Is there a `stack` command to install this package?

**Comment by tienwei** [comment]
I just did `stack install hoogle`. It also works. @stevemao

**Comment by stevemao** [comment]
I created a page on WIKI https://github.com/fp-works/2019-winter-Haskell-school/wiki/TIL
